server:
  servlet:
    context-path: /chocolate

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/project4"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
