server:
  servlet:
    context-path: /chocolate



spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/project4"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC

  web:
    resources:
      static-locations: classpath:/static/

      add-mappings: true

#
#openapi:
#  service:
#    api-docs: api-service
#    server: http://localhost:8080
#    title: API Service
#    version: 1.0.0
#    description: Mota API service
#    serverName: Server Test

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
